version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn server:app --bind 0.0.0.0:8000 --timeout 300 --workers 2
    ports:
      - 80:8000
    env_file:
      - ./.env
    volumes:
      - ./:/python-docker
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    env_file:
      - ./.env
    volumes:
      - ./:/python-docker
